### ISSUE TITLE
Sydney: Create SH script for export-graphML.

### ISSUE THREAD

**Issue by aaryani** [researchgraph/TechLauncher#15]

**Comment by kumomi** [comment]
Brief Requirements:
1. Optimal Goal: create SH script for export-graphML file.
2. Due to the data privacy, the pulling request can not happen on local machine. All the process have to happen on the Sydney University server. 
3. The server environment will be based on Ubuntu, 
4. A detailed documentation needed. README.md file will be necessary. The suggestion is to putting a set of step by step actions for .
5. Using R.Neo4j instead of using community version of Neo4j.

**Comment by aaryani** [comment]
We need to add the AWS S3 Syn function to move the GraphML to S3

**Comment by aaryani** [comment]
This task is complete. Well done 👍
